import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Domine } from 'next/font/google'; // Import Domine
import "./globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer'; 

// Configure Geist fonts
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const domine = Domine({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-domine', 
});

export const metadata: Metadata = {
  title: "James Crowe",
  description: "Personal site generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Domine:wght@400;500;600;700&display=swap"
        />
      </head>
      <body className={`${domine.variable} font-sans min-h-screen flex flex-col`}> {/* Use flex layout */}
        <Header />
        <main className="flex-1"> 
          {children}
        </main>
        <Footer /> 
      </body>
    </html>
  );
}